### ISSUE TITLE
Failing to deploy the skill

### ISSUE THREAD

**Issue by vkhazin** [vkhazin/mortgage-rates-alexa-bot#5]
Commands executed from a terminal window:
```
cd ./lambda/custom && \
  yarn install && \
  yarn test && \
  cd ../../ && \
  ask deploy
```
Last step generates the following error:
[Error]: Failed to deploy. Please ensure current working directory is the root of your skill project.

Is it possible that something wrong with the current state, if so, how do I reset it?

**Comment by amanenk** [comment]
This script a little bit differs from my original script.
Error apears bexasue file `./.ask/config` does not exist.
```
cd ./lambda/custom && \
  yarn install && \
  yarn test && \
  cd ../../ && \
  cp ./.ask/config.example ./.ask/config && \
  ask deploy
```

**Comment by vkhazin** [comment]
My mistake!
